name: invalidate-awf-cf-cache
run-name: Invalidate AWF Cloud Foundry Cache
on:
  workflow_call:
    inputs:
      distribution:
        required: true
        type: string
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
jobs:
  invalidate-awf-cf-cache:
    runs-on: ubuntu-latest
    steps:
      - id: checkout_step
        name: Checkout the main GitHub branch to get scripts
        uses: actions/checkout@v4
        with:
          sparse-checkout: .github
          fetch-depth: 0
      - id: invalidate_awf_cf_cache
        name: Invalidate AWF Cloud Foundry Cache
        run: ./.github/scripts/invalidate-aws-cf-cache.sh ${{ inputs.distribution }}
        shell: bash
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: 'eu-west-1'
