name: s1-invalidate-aws-cf-cache
run-name: Invalidate AWF Cloud Foundry Cache s1
on:
  workflow_call:
  workflow_dispatch:
jobs:
  invalidate-aws-cf-cache-d1:
    uses: ./.github/workflows/invalidate-aws-cf-cache.yml
    with:
      distribution: E16HK1VUNDFTYS
